{{- if eq (include "app.envExists" .) "true" -}}
{{- $spec := fromYaml (include "app.merged" .) -}}
{{- if $spec.configFiles -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $filename, $file := $spec.configFiles }}
  {{ $filename }}: |
    {{- include "app.configFileContent" (dict "filename" $filename "file" $file) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
