{{- if eq (include "app.envExists" .) "true" -}}
{{- $secrets := (fromYaml (include "app.merged" .)).secrets -}}
{{- if $secrets.path -}}
{{- $appName := include "app.name" . -}}
---
{{ include "common.infisicalSecret" (dict
     "name" (printf "%s-infisical" $appName)
     "labels" (include "app.labels" .)
     "envSlug" (include "app.infisicalEnv" .)
     "secretsPath" $secrets.path
     "secretName" (include "app.secretsName" .)
     "secretNamespace" .Release.Namespace) }}
{{- end }}
{{- end }}
