{{- if eq (include "app.envExists" .) "true" -}}
{{- $spec := fromYaml (include "app.merged" .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ $spec.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}
