{{- if .Values.host }}
{{- include "common.certificate" (dict
      "name" (printf "%s-tls" (include "platform-service.name" .))
      "labels" (include "platform-service.labels" .)
      "secretName" (printf "%s-tls" (include "platform-service.name" .))
      "dnsNames" (concat (list (include "platform-service.host" .)) (.Values.aliases | default list))) }}
{{- end }}
